#!/usr/bin/env python

MODE_NONE = 70
MODE_SUBSCRIBE = 71
MODE_UNSUBSCRIBE = 73
MODE_LIST = 74
MODE_UPDATE = 75
MODE_MAIL_ADD = 76
MODE_MAIL_DELETE = 77
MODE_MAIL_LIST = 78

DOWNLOAD_DIRECTORY = "/data/ryannoelk/files/podcasts"
NUMBER_OF_PODCASTS_TO_KEEP = 5
